In [11]:
from transformers.pipelines import SUPPORTED_TASKS

/home/wjc/miniconda3/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
from pprint import pprint
pprint(SUPPORTED_TASKS.keys())

dict_keys(['audio-classification', 'automatic-speech-recognition', 'text-to-audio', 'feature-extraction', 'text-classification', 'token-classification', 'question-answering', 'table-question-answering', 'visual-question-answering', 'document-question-answering', 'fill-mask', 'summarization', 'translation', 'text2text-generation', 'text-generation', 'zero-shot-classification', 'zero-shot-image-classification', 'zero-shot-audio-classification', 'image-classification', 'image-feature-extraction', 'image-segmentation', 'image-to-text', 'object-detection', 'zero-shot-object-detection', 'depth-estimation', 'video-classification', 'mask-generation', 'image-to-image'])


In [4]:
for k,v in SUPPORTED_TASKS.items():
    print(k)
    print(v)

audio-classification
{'impl': <class 'transformers.pipelines.audio_classification.AudioClassificationPipeline'>, 'tf': (), 'pt': (<class 'transformers.models.auto.modeling_auto.AutoModelForAudioClassification'>,), 'default': {'model': {'pt': ('superb/wav2vec2-base-superb-ks', '372e048')}}, 'type': 'audio'}
automatic-speech-recognition
{'impl': <class 'transformers.pipelines.automatic_speech_recognition.AutomaticSpeechRecognitionPipeline'>, 'tf': (), 'pt': (<class 'transformers.models.auto.modeling_auto.AutoModelForCTC'>, <class 'transformers.models.auto.modeling_auto.AutoModelForSpeechSeq2Seq'>), 'default': {'model': {'pt': ('facebook/wav2vec2-base-960h', '55bb623')}}, 'type': 'multimodal'}
text-to-audio
{'impl': <class 'transformers.pipelines.text_to_audio.TextToAudioPipeline'>, 'tf': (), 'pt': (<class 'transformers.models.auto.modeling_auto.AutoModelForTextToWaveform'>, <class 'transformers.models.auto.modeling_auto.AutoModelForTextToSpectrogram'>), 'default': {'model': {'pt': ('suno

In [2]:
from transformers import pipeline, QuestionAnsweringPipeline


/home/wjc/miniconda3/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [7]:
pipe = pipeline('text-classification')

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://hf-mirror.com/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
loading configuration file config.json from cache at /home/wjc/.cache/huggingface/hub/models--distilbert--distilbert-base-uncased-finetuned-sst-2-english/snapshots/714eb0fa89d2f80546fda750413ed43d93601a13/config.json
Model config DistilBertConfig {
  "_name_or_path": "distilbert/distilbert-base-uncased-finetuned-sst-2-english",
  "activation": "gelu",
  "architectures": [
    "DistilBertForSequenceClassification"
  ],
  "attention_dropout": 0.1,
  "dim": 768,
  "dropout": 0.1,
  "finetuning_task": "sst-2",
  "hidden_dim": 3072,
  "id2label": {
    "0": "NEGATIVE",
    "1": "POSITIVE"
  },
  "initializer_range": 0.02,
  "label2id": {
    "NEGATIVE": 0,
    "POSITIVE": 1
  },
  "max_position_embed

In [8]:
pipe('very good')

[{'label': 'POSITIVE', 'score': 0.9998520612716675}]

In [10]:
pipe = pipeline('text-classification', model = 'uer/roberta-base-finetuned-dianping-chinese')

loading configuration file config.json from cache at /home/wjc/.cache/huggingface/hub/models--uer--roberta-base-finetuned-dianping-chinese/snapshots/25faf1874b21e76db31ea9c396ccf2a0322e0071/config.json
Model config BertConfig {
  "_name_or_path": "uer/roberta-base-finetuned-dianping-chinese",
  "architectures": [
    "BertForSequenceClassification"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "id2label": {
    "0": "negative (stars 1, 2 and 3)",
    "1": "positive (stars 4 and 5)"
  },
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "label2id": {
    "negative (stars 1, 2 and 3)": 0,
    "positive (stars 4 and 5)": 1
  },
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.44.1",
  "type_voca

In [11]:
pipe('不行')

[{'label': 'negative (stars 1, 2 and 3)', 'score': 0.9920274615287781}]

In [12]:
from transformers import AutoModelForSequenceClassification, AutoTokenizer

# model  = AutoModelForSequenceClassification.from_pretrained('/data/wjc/models/Meta-Llama-3-8B-Instruct')
# tokenizer = AutoTokenizer.from_pretrained('/data/wjc/models/Meta-Llama-3-8B-Instruct')

# pipe = pipeline('text-classification', model = model, tokenizer = tokenizer)

In [16]:
pipe('不行')

[{'label': 'LABEL_0', 'score': 0.8429162502288818}]

In [4]:
qa_pipe = pipeline('question-answering', model = 'uer/roberta-base-chinese-extractive-qa', tokenizer = 'uer/roberta-base-chinese-extractive-qa')

/home/wjc/miniconda3/lib/python3.12/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.


In [5]:
qa_pipe

In [6]:
QuestionAnsweringPipeline

transformers.pipelines.question_answering.QuestionAnsweringPipeline

In [7]:
qa_pipe('我是谁', '我是谁')

{'score': 2.0642194620279497e-09, 'start': 2, 'end': 3, 'answer': '谁'}

In [13]:
tokenizer = AutoTokenizer.from_pretrained("uer/roberta-base-chinese-extractive-qa")
model = AutoModelForSequenceClassification.from_pretrained("uer/roberta-base-chinese-extractive-qa")

/home/wjc/miniconda3/lib/python3.12/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at uer/roberta-base-chinese-extractive-qa and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [11]:
input_text = "我觉得不太行！"
inputs = tokenizer(input_text, return_tensors="pt")

In [12]:
inputs

{'input_ids': tensor([[ 101, 2769, 6230, 2533,  679, 1922, 6121, 8013,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [13]:
res = model(**inputs)
res

SequenceClassifierOutput(loss=None, logits=tensor([[0.0294, 0.0761]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [20]:
logits = res.logits
logits = torch.softmax(logits, dim=0)
logits
pred = torch.argmax(logits).item()
pred

0

In [15]:

import torch

In [21]:
model

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(21128, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSdpaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e

In [22]:
sen = "弱小的我也有大梦想!"

In [23]:
tokenizer

BertTokenizerFast(name_or_path='uer/roberta-base-chinese-extractive-qa', vocab_size=21128, model_max_length=512, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, clean_up_tokenization_spaces=True),  added_tokens_decoder={
	0: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	100: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	101: AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	102: AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	103: AddedToken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
}

In [24]:
tokens = tokenizer.tokenize(sen)
tokens

['弱', '小', '的', '我', '也', '有', '大', '梦', '想', '!']

In [25]:
tokenizer.tokenize

<bound method PreTrainedTokenizerFast.tokenize of BertTokenizerFast(name_or_path='uer/roberta-base-chinese-extractive-qa', vocab_size=21128, model_max_length=512, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, clean_up_tokenization_spaces=True),  added_tokens_decoder={
	0: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	100: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	101: AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	102: AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	103: AddedToken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
}>

In [26]:
tokenizer.vocab

{'##隐': 20448,
 '##desk': 13039,
 '##ndi': 11874,
 '惟': 2668,
 '##tina': 10584,
 '##嫲': 15133,
 'な': 557,
 'hbl': 12502,
 '祇': 4856,
 '397': 12591,
 'jp': 9348,
 '503': 12929,
 'so': 8968,
 '##懵': 15810,
 '##邵': 19996,
 '颛': 7581,
 '##啄': 14611,
 '码': 4772,
 '娘': 2023,
 '邢': 6928,
 '##驍': 20764,
 '##蹺': 19762,
 '躬': 6717,
 'continue': 10859,
 'parker': 12495,
 '##ties': 11199,
 '##岘': 15324,
 'ては': 9418,
 '##潮': 17117,
 '睫': 4724,
 '墨': 1874,
 '##禁': 17938,
 '##记': 19438,
 '##鲸': 20898,
 '忪': 2570,
 '##仗': 13858,
 'ctrl': 8947,
 'bug': 8761,
 '##絲': 18244,
 '閉': 7273,
 '##lvin': 12745,
 'sign': 12710,
 '##＆': 21075,
 '篆': 5062,
 '##℃': 8320,
 '265': 8689,
 '##|': 13345,
 '濘': 4087,
 'x6': 12121,
 '##它': 15181,
 '##東': 16403,
 '焚': 4190,
 'ji': 12095,
 '##摒': 16091,
 '##︱': 21050,
 '◕': 475,
 'ᵒ': 335,
 'への': 11021,
 '##ɔ': 13367,
 'harry': 12296,
 '##ssion': 12726,
 '噸': 1697,
 '俐': 919,
 '##啲': 14633,
 '撵': 3068,
 '##療': 17672,
 '壮': 1896,
 'july': 8909,
 '奥': 1952,
 '沌': 3757,
 'jpg'

In [27]:
tokenizer.vocab_size

21128

In [28]:
# 将词序列转换为id序列
ids = tokenizer.convert_tokens_to_ids(tokens)
ids

[2483, 2207, 4638, 2769, 738, 3300, 1920, 3457, 2682, 106]

In [29]:
tokens = tokenizer.convert_ids_to_tokens(ids)

In [30]:
tokens

['弱', '小', '的', '我', '也', '有', '大', '梦', '想', '!']

In [31]:
tokenizer.tokenize('我')

['我']

In [32]:
ids = tokenizer.encode(sen)

In [33]:
ids

[101, 2483, 2207, 4638, 2769, 738, 3300, 1920, 3457, 2682, 106, 102]

In [34]:
str_sen = tokenizer.decode(ids)
str_sen

'[CLS] 弱 小 的 我 也 有 大 梦 想! [SEP]'

In [36]:
ids = tokenizer.encode(sen, padding="max_length", max_length=20)
ids

[101,
 2483,
 2207,
 4638,
 2769,
 738,
 3300,
 1920,
 3457,
 2682,
 106,
 102,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [37]:
atten_mask = [1 if i != 0 else 0 for i in ids]
atten_mask

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]

In [38]:
inputs = tokenizer.encode_plus(sen, return_tensors="pt", padding="max_length", max_length=20)
inputs

{'input_ids': tensor([[ 101, 2483, 2207, 4638, 2769,  738, 3300, 1920, 3457, 2682,  106,  102,
            0,    0,    0,    0,    0,    0,    0,    0]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]])}

In [39]:
inputs = tokenizer(sen, return_tensors="pt", padding="max_length", max_length=20)

In [40]:
inputs

{'input_ids': tensor([[ 101, 2483, 2207, 4638, 2769,  738, 3300, 1920, 3457, 2682,  106,  102,
            0,    0,    0,    0,    0,    0,    0,    0]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]])}

In [41]:
sens = ["弱小的我也有大梦想",
        "有梦想谁都了不起",
        "追逐梦想的心，比梦想本身，更可贵"]
res = tokenizer(sens)
res

{'input_ids': [[101, 2483, 2207, 4638, 2769, 738, 3300, 1920, 3457, 2682, 102], [101, 3300, 3457, 2682, 6443, 6963, 749, 679, 6629, 102], [101, 6841, 6852, 3457, 2682, 4638, 2552, 8024, 3683, 3457, 2682, 3315, 6716, 8024, 3291, 1377, 6586, 102]], 'token_type_ids': [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]}

In [42]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

In [45]:
import pandas as pd

data = pd.read_csv('/home/wjc/mllm/mllm_from_scratch/learn_transformers/transformers-code/01-Getting Started/04-model/ChnSentiCorp_htl_all.csv')
data


,label,review
0,1,"距离川沙公路较近,但是公交指示不对,如果是""蔡陆线""的话,会非常麻烦.建议用别的路线.房间较..."
1,1,商务大床房，房间很大，床有2M宽，整体感觉经济实惠不错!
2,1,早餐太差，无论去多少人，那边也不加食品的。酒店应该重视一下这个问题了。房间本身很好。
3,1,宾馆在小街道上，不大好找，但还好北京热心同胞很多~宾馆设施跟介绍的差不多，房间很小，确实挺小...
4,1,"CBD中心,周围没什么店铺,说5星有点勉强.不知道为什么卫生间没有电吹风"
...,...,...
7761,0,尼斯酒店的几大特点：噪音大、环境差、配置低、服务效率低。如：1、隔壁歌厅的声音闹至午夜3点许...
7762,0,盐城来了很多次，第一次住盐阜宾馆，我的确很失望整个墙壁黑咕隆咚的，好像被烟熏过一样家具非常的...
7763,0,看照片觉得还挺不错的，又是4星级的，但入住以后除了后悔没有别的，房间挺大但空空的，早餐是有但...
7764,0,我们去盐城的时候那里的最低气温只有4度，晚上冷得要死，居然还不开空调，投诉到酒店客房部，得到...


In [46]:
data = data.dropna()
data

,label,review
0,1,"距离川沙公路较近,但是公交指示不对,如果是""蔡陆线""的话,会非常麻烦.建议用别的路线.房间较..."
1,1,商务大床房，房间很大，床有2M宽，整体感觉经济实惠不错!
2,1,早餐太差，无论去多少人，那边也不加食品的。酒店应该重视一下这个问题了。房间本身很好。
3,1,宾馆在小街道上，不大好找，但还好北京热心同胞很多~宾馆设施跟介绍的差不多，房间很小，确实挺小...
4,1,"CBD中心,周围没什么店铺,说5星有点勉强.不知道为什么卫生间没有电吹风"
...,...,...
7761,0,尼斯酒店的几大特点：噪音大、环境差、配置低、服务效率低。如：1、隔壁歌厅的声音闹至午夜3点许...
7762,0,盐城来了很多次，第一次住盐阜宾馆，我的确很失望整个墙壁黑咕隆咚的，好像被烟熏过一样家具非常的...
7763,0,看照片觉得还挺不错的，又是4星级的，但入住以后除了后悔没有别的，房间挺大但空空的，早餐是有但...
7764,0,我们去盐城的时候那里的最低气温只有4度，晚上冷得要死，居然还不开空调，投诉到酒店客房部，得到...


In [48]:
from torch.utils.data import Dataset, DataLoader

In [49]:
class MyDataset(Dataset):
    def __init__(self) -> None:
        super().__init__()
        self.data = pd.read_csv('/home/wjc/mllm/mllm_from_scratch/learn_transformers/transformers-code/01-Getting Started/04-model/ChnSentiCorp_htl_all.csv')
        self.data = self.data.dropna()
    def __getitem__(self, index):
        return self.data.iloc[index]['review'], self.data.iloc[index]['label']
    
    def __len__(self):
        return len(self.data)

In [50]:
import pandas as pd
dataset  = MyDataset()
for i in range(5):
    print(dataset[i])

('距离川沙公路较近,但是公交指示不对,如果是"蔡陆线"的话,会非常麻烦.建议用别的路线.房间较为简单.', 1)
('商务大床房，房间很大，床有2M宽，整体感觉经济实惠不错!', 1)
('早餐太差，无论去多少人，那边也不加食品的。酒店应该重视一下这个问题了。房间本身很好。', 1)
('宾馆在小街道上，不大好找，但还好北京热心同胞很多~宾馆设施跟介绍的差不多，房间很小，确实挺小，但加上低价位因素，还是无超所值的；环境不错，就在小胡同内，安静整洁，暖气好足-_-||。。。呵还有一大优势就是从宾馆出发，步行不到十分钟就可以到梅兰芳故居等等，京味小胡同，北海距离好近呢。总之，不错。推荐给节约消费的自助游朋友~比较划算，附近特色小吃很多~', 1)
('CBD中心,周围没什么店铺,说5星有点勉强.不知道为什么卫生间没有电吹风', 1)


In [51]:
def collate_func(batch):
    texts, labels = [], []
    for item in batch:
        texts.append(item[0])
        labels.append(item[1])
    inputs = tokenizer(texts, return_tensors="pt", padding="max_length", max_length=128,                # 启用自动填充
        truncation=True, )
    inputs['labels'] = torch.tensor(labels)
    return inputs

In [52]:
from torch.utils.data import DataLoader

train_loader = DataLoader(dataset, batch_size=2, shuffle=True, collate_fn=collate_func)
vaild_loader = DataLoader(dataset, batch_size=2, shuffle=False, collate_fn=collate_func)

In [53]:
train_loader

In [54]:
vaild_loader

In [15]:
import torch

In [57]:
next(enumerate(vaild_loader))[1]

{'input_ids': tensor([[ 101, 6655, 4895, 2335, 3763, 1062, 6662, 6772, 6818,  117,  852, 3221,
         1062,  769, 2900, 4850,  679, 2190,  117, 1963, 3362, 3221,  107, 5918,
         7355, 5296,  107, 4638, 6413,  117,  833, 7478, 2382, 7937, 4172,  119,
         2456, 6379, 4500, 1166, 4638, 6662, 5296,  119, 2791, 7313, 6772,  711,
         5042, 1296,  119,  102,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0],
        [ 101, 1555, 1218, 1920, 2414, 2791, 8024, 2791, 7313, 2523, 1920, 8024,
         2414, 3300,  100, 2160, 8024

In [17]:
model

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(21128, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSdpaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e

In [18]:
from torch.optim import Adam
optimizer = Adam(model.parameters(), lr=2e-5)

In [43]:
from torch.optim import Adam


if torch.cuda.is_available():
    model = model.cuda()

In [44]:
optimizer

Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    capturable: False
    differentiable: False
    eps: 1e-08
    foreach: None
    fused: None
    lr: 2e-05
    maximize: False
    weight_decay: 0
)

In [45]:
with torch.inference_mode():

    for batch in vaild_loader:
        if torch.cuda.is_available():
            batch = {k: v.cuda() for k, v in batch.items}
        print(batch)


TypeError: 'method' object is not iterable

In [46]:
def evaluate():
    model.eval()
    acc_num = 0
    with torch.inference_mode():
        for batch in vaild_loader:
            if torch.cuda.is_available():
                batch = {k: v.cuda() for k, v in batch.items()}
                print(batch.items)
            output = model(**batch)
            pred = torch.argmax(output.logits, dim = -1)
            acc_num += (pred.long() == batch['labels'].long()).float().sum()
    return  acc_num/len(vaild_loader)
def train(epoch=3 , log_step=100):
    global_step =0
    for ep in range(epoch):
        model.train()
        for batch in train_loader:
            if torch.cuda.is_available():
                batch = {k: v.cuda() for k, v in batch.items}
            optimizer.zero_grad()
            output = model(**batch)
            output.loss.backward()
            optimizer.step()
            if global_step % log_step == 0:
                print(f"ep: {ep}, global_step: {global_step}, loss: {output.loss.item()}")
            global_step += 1
        acc = evaluate()
        print(f"ep: {ep}, acc: {acc}")


In [56]:
train()

TypeError: 'method' object is not iterable

In [3]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from datasets import load_dataset

In [2]:
!pip install datasets

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 480.6/480.6 kB 1.4 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.4/194.4 kB 15.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 14.0 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.4/63.4 kB 2.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 283.6/283.6 kB 5.0 MB/s eta 0:00:0000:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.0/131.0 kB 2.7 MB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 243.6/243.6 kB 20.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 336.9/336.9 kB 14.5 MB/s eta 0:00:00


In [1]:
### 简化版本

In [3]:
import torch
import torch.nn as nn
import math

class selfattention(nn.Module):
    def __init__(self, hidden_dim: int = 512) -> None:
        super().__init__()

        self.hidden_dim = hidden_dim
        self.q_proj = nn.Linear(hidden_dim, hidden_dim)
        self.k_proj = nn.Linear(hidden_dim, hidden_dim)
        self.v_proj = nn.Linear(hidden_dim, hidden_dim)


    def forward(self, x):

        q = self.q_proj(x)
        k = self.k_proj(x)
        v = self.v_proj(x)

        atten_value = torch.matmul(q, k.transpose(-1, -2)
                                   )
        atten_weight = torch.softmax(atten_value / math.sqrt(self.hidden_dim),dim=-1)
        output = torch.matmul(atten_weight, v)
        return output

x= torch.rand(2,3,4)
self_atten = selfattention(4)
res = self_atten(x)

    


In [4]:
res

tensor([[[-0.3434, -0.1586, -0.0692,  0.5237],
         [-0.3405, -0.1619, -0.0668,  0.5269],
         [-0.3432, -0.1589, -0.0692,  0.5237]],

        [[-0.3293, -0.3130, -0.1228,  0.4577],
         [-0.3289, -0.3130, -0.1239,  0.4602],
         [-0.3289, -0.3130, -0.1239,  0.4604]]], grad_fn=<UnsafeViewBackward0>)

In [8]:
class self_attenv2(nn.Module):
    def __init__(self, dim):
        super().__init__()
        self.dim = dim
        self.qkv_proj = nn.Linear(dim, dim*3)

    def forward(self,x):
        qkv = self.qkv_proj(x)
        q,k,v = torch.split(qkv, self.dim, dim=-1)
        atten_value = q @ k.transpose(-1, -2)
        atten_weight = torch.softmax(atten_value / math.sqrt(self.dim), dim=-1) @ v
        return atten_weight
    
x= torch.rand(2,3,4)
self_atten = self_attenv2(4)
res = self_atten(x)
res

        

tensor([[[ 0.4147, -0.2185, -0.0133,  0.6002],
         [ 0.4145, -0.2180, -0.0134,  0.5999],
         [ 0.4155, -0.2197, -0.0121,  0.6017]],

        [[ 0.3231,  0.0105, -0.1812,  0.6127],
         [ 0.3246,  0.0080, -0.1790,  0.6140],
         [ 0.3288,  0.0018, -0.1744,  0.6169]]], grad_fn=<UnsafeViewBackward0>)

In [13]:
class self_attenv3(nn.Module):
    def __init__(self, dim):
        super().__init__()
        self.dim = dim
        self.qkv_proj = nn.Linear(dim, dim*3)
        self.att_drop = nn.Dropout(0.1)
        self.out_proj = nn.Linear(dim, dim)
        

    def forward(self,x, mask=None):
        qkv = self.qkv_proj(x)
        q,k,v = torch.split(qkv, self.dim, dim=-1)
        atten_value = q @ k.transpose(-1,-2)/math.sqrt(self.dim)
        if mask is not None:
            atten_value = atten_value.masked_fill(mask == 0, float('1e-20'))
        atten_weight = torch.softmax(atten_value, dim=-1)
        atten_weight = self.att_drop(atten_weight)
        atten_weight = atten_weight @ v
        atten_weight = self.out_proj(atten_weight)

        return atten_weight
    
x= torch.rand(2,3,4)
mask = torch.tensor([[1,1,0],[1,0,0]])
print(mask.shape)
print(mask)
mask = mask.unsqueeze(1)
print(mask.shape)
print(mask)
mask = mask.repeat(1,3,1)
print(mask.shape)
mask

self_atten = self_attenv3(4)
res = self_atten(x, mask)
res


torch.Size([2, 3])
tensor([[1, 1, 0],
        [1, 0, 0]])
torch.Size([2, 1, 3])
tensor([[[1, 1, 0]],

        [[1, 0, 0]]])
torch.Size([2, 3, 3])


tensor([[[-0.0266, -0.3372, -0.0219,  0.3664],
         [-0.0289, -0.3353, -0.0213,  0.3676],
         [-0.1421, -0.2271, -0.0186,  0.4151]],

        [[-0.0778, -0.2818,  0.0121,  0.3841],
         [-0.1552, -0.2064,  0.0116,  0.4001],
         [-0.0773, -0.2828,  0.0119,  0.3836]]], grad_fn=<ViewBackward0>)

In [14]:
import torch

In [37]:
class MultiHeadAttention(nn.Module):
    def __init__(self, dim, head_nums):
        super().__init__()
        self.dim = dim
        self.head_nums = head_nums
        self.head_dim = dim // head_nums

        self.q_proj = nn.Linear(dim, dim)
        self.k_proj = nn.Linear(dim, dim)
        self.v_proj = nn.Linear(dim, dim)
        self.out_proj = nn.Linear(dim, dim)

        self.att_drop = nn.Dropout(0.1)

    def forward(self, x, mask=None):
        batch, sqlen, _ = x.size()
        q = self.q_proj(x)
        k = self.k_proj(x)
        v = self.v_proj(x)

        q = q.view(batch, sqlen, self.head_nums, self.head_dim).transpose(1, 2)
        k = k.view(batch, sqlen, self.head_nums, self.head_dim).transpose(1, 2)
        v = v.view(batch, sqlen, self.head_nums, self.head_dim).transpose(1, 2)

        atten_value = q @ k.transpose(-2, -1) / math.sqrt(self.head_dim)
        if mask is not None:
            atten_value = atten_value.masked_fill(mask == 0, float('1e-20'))
        atten_weight = torch.softmax(atten_value, dim=-1)
        atten_weight = self.att_drop(atten_weight)

        atten_weight = atten_weight @ v
        atten_weight = atten_weight.transpose(1, 2).contiguous().view(batch, sqlen, self.dim)
        atten_weight = self.out_proj(atten_weight)
        return atten_weight
    
x= torch.rand(2,3,4)
mask = torch.tensor([[1,1,0],[1,0,0]])
print(mask.shape)
print(mask)

mask = mask.unsqueeze(1)
print(mask.shape)

mask = mask.repeat(1,3,1)
print(mask.shape)
mask

multi_head_atten = MultiHeadAttention(4, 2)
res = multi_head_atten(x, mask)
res

torch.Size([2, 3])
tensor([[1, 1, 0],
        [1, 0, 0]])
torch.Size([2, 1, 3])
torch.Size([2, 3, 3])


tensor([[[-0.3476, -0.6457, -0.3724, -0.2713],
         [-0.3718, -0.5966, -0.3963, -0.2944],
         [-0.3500, -0.6461, -0.3714, -0.2697]],

        [[-0.4167, -0.5465, -0.4235, -0.2751],
         [-0.4932, -0.6148, -0.3497, -0.1838],
         [-0.4934, -0.6163, -0.3503, -0.1841]]], grad_fn=<ViewBackward0>)

In [39]:
class simpleDecoder(nn.Module):
    def __init__(self, dim, head_nums):
        super().__init__()
        self.dim = dim
        self.head_nums = head_nums
        self.head_dim = dim // head_nums

        self.atten_layerNorm = nn.LayerNorm(dim, eps=1e-5)

        self.q_proj = nn.Linear(dim, dim)
        self.k_proj = nn.Linear(dim, dim)
        self.v_proj = nn.Linear(dim, dim)
        self.out_proj = nn.Linear(dim, dim)

        self.att_drop = nn.Dropout(0.1)
        # self.fnn_layernorm1 = nn.LayerNorm(dim, esp = 1e-5)

        self.up = nn.Linear(dim, dim * 4)
        self.down = nn.Linear(dim * 4, dim)
        self.fnn_layernorm2 = nn.LayerNorm(dim, eps = 1e-5)
        self.act_fn = nn.GELU()
        self.fnn_drop = nn.Dropout(0.1)

    def atten_output(self, q, k, v, mask=None):
        atten_value = q @ k.transpose(-2, -1) / math.sqrt(self.head_dim)

        if mask is not None:
            mask = mask.tril()
            atten_value = atten_value.masked_fill(mask == 0, float('-inf'))
        else:
            mask = torch.ones_like(atten_value).tril()
            atten_value = atten_value.masked_fill(mask == 0, float('-inf'))

        
        print(mask.shape)
        print(mask)

        atten_weight = torch.softmax(atten_value, dim=-1)
        atten_weight = self.att_drop(atten_weight)
        atten_weight = atten_weight @ v
        batch, head_nums, sqlen, head_dim = atten_weight.size()
        atten_weight = atten_weight.transpose(1, 2).contiguous().view(batch, sqlen, self.dim)
        atten_weight = self.out_proj(atten_weight)
        return atten_weight


    def block_block(self, x, mask=None):
        batch, sqlen, _ = x.size()
        q = self.q_proj(x)
        k = self.k_proj(x)
        v = self.v_proj(x)

        q = q.view(batch, sqlen, self.head_nums, self.head_dim).contiguous().transpose(1, 2)
        k = k.view(batch, sqlen, self.head_nums, self.head_dim).contiguous().transpose(1, 2)
        v = v.view(batch, sqlen, self.head_nums, self.head_dim).contiguous().transpose(1, 2)

        atten = self.atten_output(q, k, v, mask)
        atten = atten + x
        atten = self.atten_layerNorm(atten)
        return atten
    def fnn_block(self, x):
        up = self.up(x)
        up = self.act_fn(up)
        down = self.down(up)
        return self.fnn_layernorm2(down + x)
    
    def forward(self, x, mask=None):
        x = self.block_block(x, mask)
        x = self.fnn_block(x)
        return x
    
class decoder(nn.Module):
    def __init__(self, dim, head_nums, layers):
        super().__init__()
        self.layer_list = nn.ModuleList([simpleDecoder(dim, head_nums) for _ in range(layers)])
        self.emb = nn.Embedding(100, dim)
        self.out = nn.Linear(dim, 100)

    def forward(self, x, mask=None):
        x = self.emb(x)
        for i,l in enumerate(self.layer_list):
            x = l(x, mask)
        print(x.shape)
        x = self.out(x)
        return torch.softmax(x, dim=-1)
        

x = torch.rand(3, 4, 64)
net = simpleDecoder(64, 8)
mask = (
    torch.tensor([[1, 1, 1, 1], [1, 1, 0, 0], [1, 1, 1, 0]])
    .unsqueeze(1)
    .unsqueeze(2)
    .repeat(1, 8, 4, 1)
)

net(x, mask).shape



torch.Size([3, 8, 4, 4])
tensor([[[[1, 0, 0, 0],
          [1, 1, 0, 0],
          [1, 1, 1, 0],
          [1, 1, 1, 1]],

         [[1, 0, 0, 0],
          [1, 1, 0, 0],
          [1, 1, 1, 0],
          [1, 1, 1, 1]],

         [[1, 0, 0, 0],
          [1, 1, 0, 0],
          [1, 1, 1, 0],
          [1, 1, 1, 1]],

         [[1, 0, 0, 0],
          [1, 1, 0, 0],
          [1, 1, 1, 0],
          [1, 1, 1, 1]],

         [[1, 0, 0, 0],
          [1, 1, 0, 0],
          [1, 1, 1, 0],
          [1, 1, 1, 1]],

         [[1, 0, 0, 0],
          [1, 1, 0, 0],
          [1, 1, 1, 0],
          [1, 1, 1, 1]],

         [[1, 0, 0, 0],
          [1, 1, 0, 0],
          [1, 1, 1, 0],
          [1, 1, 1, 1]],

         [[1, 0, 0, 0],
          [1, 1, 0, 0],
          [1, 1, 1, 0],
          [1, 1, 1, 1]]],


        [[[1, 0, 0, 0],
          [1, 1, 0, 0],
          [1, 1, 0, 0],
          [1, 1, 0, 0]],

         [[1, 0, 0, 0],
          [1, 1, 0, 0],
          [1, 1, 0, 0],
          [1, 1, 0,

torch.Size([3, 4, 64])

In [25]:
torch.tensor([[1, 1, 1, 1], [1, 1, 0, 0], [1, 1, 1, 0]])

tensor([[1, 1, 1, 1],
        [1, 1, 0, 0],
        [1, 1, 1, 0]])

In [27]:
torch.tensor([[1, 1, 1, 1], [1, 1, 0, 0], [1, 1, 1, 0]]).unsqueeze(1)

tensor([[[1, 1, 1, 1]],

        [[1, 1, 0, 0]],

        [[1, 1, 1, 0]]])

In [30]:
mask.size()

torch.Size([3, 8, 4, 4])

In [50]:
class GroupQueryAttention(nn.Module):
    def __init__(self, dim, head_nums, nums_key_value_head):
        super().__init__()
        self.dim = dim
        self.head_nums = head_nums
        self.head_dim = dim // head_nums
        self.nums_key_value_head = nums_key_value_head
        assert dim % head_nums == 0
        assert head_nums % nums_key_value_head == 0

        self.q_proj = nn.Linear(dim, dim)
        self.k_proj = nn.Linear(dim, nums_key_value_head * self.head_dim)
        self.v_proj = nn.Linear(dim, nums_key_value_head * self.head_dim)
        self.out_proj = nn.Linear(dim, dim)

        self.atten_drop = nn.Dropout(0.1)

    def forward(self, x, mask=None):
        batch, seqlen, _ = x.size()
        q = self.q_proj(x)
        k = self.k_proj(x)
        v = self.v_proj(x)

        q= q.view(batch, seqlen, self.head_nums, self.head_dim).transpose(1, 2)
        k = k.view(batch, seqlen, self.nums_key_value_head, self.head_dim).transpose(1, 2)
        v = v.view(batch, seqlen, self.nums_key_value_head, self.head_dim).transpose(1, 2)

        k = k.repeat_interleave(self.head_nums // self.nums_key_value_head, dim=1)
        v = v.repeat_interleave(self.head_nums // self.nums_key_value_head, dim=1)

        atten_value = q @ k.transpose(-2, -1) / math.sqrt(self.head_dim)
        if mask is not None:
            atten_value = atten_value.masked_fill(mask == 0, float('-inf'))

        atten_weight = torch.softmax(atten_value, dim=-1)
        atten_weight = self.atten_drop(atten_weight)
        atten_weight = atten_weight @ v
        atten_weight = atten_weight.transpose(1, 2).contiguous().view(batch, seqlen, self.dim)
        atten_weight = self.out_proj(atten_weight)
        return atten_weight
    
x = torch.rand(3, 2, 128)
# mask = torch.tensor([[1, 1, 0], [1, 0, 0]])
mask = torch.tensor([[1, 1], [1, 0], [1, 1]])
mask = mask.unsqueeze(1)

print(mask.shape)
print(mask)
mask = mask.repeat(1, 8, 1)

print(mask.shape)
print(mask)

mask = mask.unsqueeze(2)
print(mask.shape)
print(mask)
mask = mask.repeat(1, 1, 2, 1)
print(mask.shape)
net = GroupQueryAttention(128, 8, 2)
res = net(x, mask)
res





torch.Size([3, 1, 2])
tensor([[[1, 1]],

        [[1, 0]],

        [[1, 1]]])
torch.Size([3, 8, 2])
tensor([[[1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 0],
         [1, 0],
         [1, 0],
         [1, 0],
         [1, 0],
         [1, 0],
         [1, 0],
         [1, 0]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1]]])
torch.Size([3, 8, 1, 2])
tensor([[[[1, 1]],

         [[1, 1]],

         [[1, 1]],

         [[1, 1]],

         [[1, 1]],

         [[1, 1]],

         [[1, 1]],

         [[1, 1]]],


        [[[1, 0]],

         [[1, 0]],

         [[1, 0]],

         [[1, 0]],

         [[1, 0]],

         [[1, 0]],

         [[1, 0]],

         [[1, 0]]],


        [[[1, 1]],

         [[1, 1]],

         [[1, 1]],

         [[1, 1]],

         [[1, 1]],

         [[1, 1]],

         [[1, 1]

tensor([[[ 6.6666e-03, -9.9160e-02,  1.1379e-01,  1.8518e-01, -3.6224e-01,
          -2.9855e-02, -4.7384e-02, -3.5234e-01, -6.2337e-02, -9.0485e-02,
           2.9214e-01,  3.5239e-02,  1.1518e-01,  5.7160e-02, -6.6458e-04,
          -1.5728e-01, -3.1226e-01, -3.0979e-01,  1.6878e-01,  2.9110e-01,
          -4.4592e-02,  1.9372e-01,  1.0063e-01,  4.5153e-02, -3.2966e-02,
          -2.2860e-01,  8.6246e-02, -3.2824e-01,  2.2151e-03,  2.0743e-01,
           1.3626e-01,  4.8235e-02,  6.5652e-02, -1.4964e-01, -2.2121e-01,
          -1.9635e-01,  8.0347e-02, -1.5565e-01,  2.5814e-02,  1.8342e-01,
           1.9436e-01,  8.1992e-02,  1.9683e-01, -1.2243e-01, -4.2661e-02,
           1.4049e-01,  1.2786e-01, -6.8061e-02,  8.5531e-02,  9.6429e-02,
          -1.7822e-01, -1.8240e-01,  1.1726e-01, -3.4998e-02,  1.3788e-01,
          -1.1562e-01, -2.5462e-02, -2.3137e-01,  1.1592e-02,  5.5436e-02,
          -5.3756e-03,  1.0917e-01, -3.1750e-01,  3.4759e-01,  2.1341e-01,
           9.5893e-02,  1